### ISSUE TITLE
"mgm_03" is not accessible through Warps, despite being a valid map.

### ISSUE THREAD

**Issue by getCursorsExe** [JCog/fp#87] opened 2024-04-26 18:33 UTC
Can be accessed with cheat codes. Attemting to view the locations menu while in this room will crash the game. The only way to exit this room is to use Bosses tab instead.

**Comment by JCog** [comment] 2024-04-26 21:43
Are you sure you have the right room? Seems to be working fine to me. I tested it on both emu and console in both US and JP.
![image](https://github.com/JCog/fp/assets/42006114/1e60d45b-c2ec-448d-9a13-c3a4c7885bd8)

**Comment by JCog** [comment] 2024-07-24 09:07
Closing this since I can't reproduce it and there's been no follow-up.

**Closed by JCog** 2024-07-24 09:07 UTC
